FROM nginx:1.27.1

COPY home_page/home.html /usr/share/nginx/html/
COPY about_us_page/aboutus.html /usr/share/nginx/html/
COPY contact_page/contact.html /usr/share/nginx/html/
COPY assets/ip.jpg /usr/share/nginx/html/