version: "3"

services:
  IP_Calculator:
    build:
      context: ./template
      dockerfile: Dockerfile
    container_name: CalcluatorIP
    ports:
      - "8080:8080"
    volumes:
      - /CalcluatorIP/template/
    